[package]
name = "turmoil"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "1.9"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
tokio = { version = "1.19.2", features = ["rt", "sync"] }
tokio-test = { version = "0.4.2" }
